services:
  bak-server:
    extends:
      file: bak/compose.yaml
      service: server
    networks:
      backend:
        aliases:
          - bak.imovies.ch
  ca-server:
    extends:
      file: ca/compose.yaml
      service: server
    environment:
      - BAK_HOST=bak.imovies.ch:8000
      - LOG_HOST=log.imovies.ch:6514
    networks:
      backend:
        aliases:
          - ca.imovies.ch
    depends_on:
      log-server:
        condition: service_started
  ca-scheduled-backup:
    extends:
      file: ca/compose.yaml
      service: scheduled-backup
    networks:
      backend:
    depends_on:
      bak-server:
        condition: service_started
  db-server:
    extends:
      file: db/compose.yaml
      service: server
    networks:
      backend:
        aliases:
          - db.imovies.ch
  db-scheduled-backup:
    extends:
      file: db/compose.yaml
      service: scheduled-backup
    networks:
      backend:
    depends_on:
      bak-server:
        condition: service_started
  db-logger:
    extends:
      file: db/compose.yaml
      service: logger
    networks:
      backend:
    depends_on:
      log-server:
        condition: service_started
  log-server:
    extends:
      file: log/compose.yaml
      service: server
    networks:
      backend:
        aliases:
          - log.imovies.ch
  log-scheduled-backup:
    extends:
      file: log/compose.yaml
      service: scheduled-backup
    networks:
      backend:
    depends_on:
      bak-server:
        condition: service_started
  web-server:
    extends:
      file: web/compose.yaml
      service: server
    environment:
      - DATABASE_HOST=db.imovies.ch:3306
      - CA_HOST=ca.imovies.ch:8000
      - LOG_HOST=log.imovies.ch:6514
    networks:
      - backend
    depends_on:
      ca-server:
        condition: service_started
      db-server:
        condition: service_healthy
      log-server:
        condition: service_started
  web-proxy:
    extends:
      file: web/compose.yaml
      service: proxy
    environment:
      - WEB_SERVER_HOST=web-server:8000
    networks:
      - backend
    depends_on:
      web-server:
        condition: service_started
networks:
  backend:
volumes:
  bak_data:
  ca_data:
  db_data:
  db_logs:
  log_data:
secrets:
  bak_cert:
    file: bak/secrets/bak.imovies.ch.crt
  bak_key:
    file: bak/secrets/bak.imovies.ch.key
  bak_htpasswd:
    file: bak/secrets/.htpasswd
  ca_cert:
    file: ca/secrets/ca.imovies.ch.crt
  ca_key:
    file: ca/secrets/ca.imovies.ch.key
  ca_root_cert:
    file: ca/secrets/root.imovies.ch.crt
  ca_root_key:
    file: ca/secrets/root.imovies.ch.key
  ca_bak_repository:
    file: secrets/ca/bak_repository.txt
  ca_bak_password:
    file: ca/secrets/bak_password.txt
  db_cert:
    file: db/secrets/db.imovies.ch.crt
  db_key:
    file: db/secrets/db.imovies.ch.key
  db_root_password:
    file: db/secrets/db_root_password.txt
  db_password:
    file: db/secrets/db_password.txt
  db_bak_repository:
    file: secrets/db/bak_repository.txt
  db_bak_password:
    file: db/secrets/bak_password.txt
  log_cert:
    file: log/secrets/log.imovies.ch.crt
  log_key:
    file: log/secrets/log.imovies.ch.key
  log_bak_repository:
    file: secrets/log/bak_repository.txt
  log_bak_password:
    file: log/secrets/bak_password.txt
  web_cert:
    file: web/secrets/web.imovies.ch.crt
  web_key:
    file: web/secrets/web.imovies.ch.key
  web_secret_key:
    file: web/secrets/web_secret_key.txt
  web_csrf_secret-key:
    file: web/secrets/web_csrf_secret_key.txt
