services:
  bak-server:
    extends:
      file: bak/compose.yaml
      service: server
    networks:
      backend:
        aliases:
          - bak.imovies.ch
  ca-server:
    extends:
      file: ca/compose.yaml
      service: server
    environment:
      - BAK_HOST=bak.imovies.ch:8000
      - LOG_HOST=log.imovies.ch:6514
    networks:
      backend:
        aliases:
          - ca.imovies.ch
    depends_on:
      log-server:
        condition: service_started
  ca-scheduled-backup:
    extends:
      file: ca/compose.yaml
      service: scheduled-backup
    networks:
      backend:
    depends_on:
      bak-server:
        condition: service_started
  db-server:
    extends:
      file: db/compose.yaml
      service: server
    networks:
      backend:
        aliases:
          - db.imovies.ch
  db-scheduled-backup:
    extends:
      file: db/compose.yaml
      service: scheduled-backup
    networks:
      backend:
    depends_on:
      bak-server:
        condition: service_started
  db-logger:
    extends:
      file: db/compose.yaml
      service: logger
    networks:
      backend:
    depends_on:
      log-server:
        condition: service_started
  log-server:
    extends:
      file: log/compose.yaml
      service: server
    networks:
      backend:
        aliases:
          - log.imovies.ch
  log-scheduled-backup:
    extends:
      file: log/compose.yaml
      service: scheduled-backup
    networks:
      backend:
    depends_on:
      bak-server:
        condition: service_started
  web-server:
    extends:
      file: web/compose.yaml
      service: server
    environment:
      - DATABASE_HOST=db.imovies.ch:3306
      - CA_HOST=ca.imovies.ch:8000
      - LOG_HOST=log.imovies.ch:6514
    networks:
      - backend
    depends_on:
      ca-server:
        condition: service_started
      db-server:
        condition: service_healthy
      log-server:
        condition: service_started
  web-proxy:
    extends:
      file: web/compose.yaml
      service: proxy
    environment:
      - WEB_SERVER_HOST=web-server:8000
    networks:
      - backend
    depends_on:
      web-server:
        condition: service_started
networks:
  backend:
volumes:
  bak-data:
  ca-data:
  db-data:
  db-logs:
  log-data:
secrets:
  bak-cert:
    file: bak/secrets/bak.imovies.ch.crt
  bak-key:
    file: bak/secrets/bak.imovies.ch.key
  bak-htpasswd:
    file: bak/secrets/.htpasswd
  ca-cert:
    file: ca/secrets/ca.imovies.ch.crt
  ca-key:
    file: ca/secrets/ca.imovies.ch.key
  ca-root-cert:
    file: ca/secrets/root.imovies.ch.crt
  ca-root-key:
    file: ca/secrets/root.imovies.ch.key
  ca-bak-repository:
    file: secrets/ca/bak_repository.txt
  ca-bak-password:
    file: ca/secrets/bak_password.txt
  db-cert:
    file: db/secrets/db.imovies.ch.crt
  db-key:
    file: db/secrets/db.imovies.ch.key
  db-root-password:
    file: db/secrets/db_root_password.txt
  db-password:
    file: db/secrets/db_password.txt
  db-bak-repository:
    file: secrets/db/bak_repository.txt
  db-bak-password:
    file: db/secrets/bak_password.txt
  log-cert:
    file: log/secrets/log.imovies.ch.crt
  log-key:
    file: log/secrets/log.imovies.ch.key
  log-bak-repository:
    file: secrets/log/bak_repository.txt
  log-bak-password:
    file: log/secrets/bak_password.txt
  web-cert:
    file: web/secrets/web.imovies.ch.crt
  web-key:
    file: web/secrets/web.imovies.ch.key
  web-secret-key:
    file: web/secrets/web_secret_key.txt
  web-csrf-secret-key:
    file: web/secrets/web_csrf_secret_key.txt
