services:
  ca-server:
    extends:
      file: ca/compose.yaml
      service: server
    networks:
      backend:
        aliases:
          - ca.imovies.ch
    depends_on:
      log-server:
        condition: service_started
  db-db:
    extends:
      file: db/compose.yaml
      service: db
    networks:
      backend:
        aliases:
          - db.imovies.ch
  log-server:
    extends:
      file: log/compose.yaml
      service: server
    networks:
      backend:
        aliases:
          - log.imovies.ch
  web-server:
    extends:
      file: web/compose.yaml
      service: server
    environment:
      - DATABASE_HOST=db.imovies.ch:3306
      - CA_HOST=ca.imovies.ch:8000
    networks:
      - backend
    depends_on:
      ca-server:
        condition: service_started
      db-db:
        condition: service_healthy
      log-server:
        condition: service_started
  web-nginx:
    extends:
      file: web/compose.yaml
      service: nginx
    networks:
      - backend
    depends_on:
      web-server:
        condition: service_started
networks:
  backend:
volumes:
  ca-data:
  db-data:
  log-data:
secrets:
  db-password:
    file: db/db_password.txt
  web-secret-key:
    file: web/web_secret_key.txt
