version: '3'

services:
  flask_app:
    build:
      context: ./web/
      dockerfile: Dockerfile
    expose:
      - "8000"

  nginx:
    build:
      context: ./web/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - flask_app
