---
roles:
  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker

  - name: geerlingguy.pip
    src: https://github.com/geerlingguy/ansible-role-pip

collections:
  - name: community.general

  - name: community.docker
