services:
  server:
    image: restic/rest-server:latest
    volumes:
      - ./certs:/etc/ssl/certs:ro
      - bak-data:/data
      - ./.htpasswd:/data/.htpasswd:ro
    environment:
      - 'OPTIONS=--append-only --private-repos --tls --tls-cert /etc/ssl/certs/bak.imovies.ch.crt --tls-key /etc/ssl/certs/bak.imovies.ch.key'
    ports:
      - "${BAK_PORT}:8000"
volumes:
  bak-data:
