services:
  server:
    build:
      context: .
    restart: unless-stopped
    hostname: bak
    volumes:
      - ./certs:/etc/ssl/certs:ro
      - bak-data:/app/data
      - ./.htpasswd:/app/data/.htpasswd:ro
    environment:
      - TZ=Etc/UTC
      - OPTIONS=--append-only --private-repos --tls --tls-cert /etc/ssl/certs/bak.imovies.ch.crt --tls-key /etc/ssl/certs/bak.imovies.ch.key
    ports:
      - "${BAK_PORT}:8000"
    user: 10001:10001
volumes:
  bak-data:
