services:
  server:
    build:
      context: server
    restart: unless-stopped
    hostname: bak
    secrets:
      - bak_cert
      - bak_key
      - bak_htpasswd
    volumes:
      - bak_data:/app/data
    environment:
      - TZ=Etc/UTC
      - OPTIONS=--append-only --htpasswd-file /run/secrets/bak_htpasswd --private-repos --tls --tls-cert /run/secrets/bak_cert --tls-key /run/secrets/bak_key
    ports:
      - "${BAK_PORT}:8000"
    user: 10001:10001
volumes:
  bak_data:
secrets:
  bak_cert:
    file: secrets/bak.imovies.ch.crt
  bak_key:
    file: secrets/bak.imovies.ch.key
  bak_htpasswd:
    file: secrets/.htpasswd
