---
  - name: "Configure Backup server locally (firewall rules)"
    hosts: localhost
    connection: local 
    become: yes
    tasks:

    - name: Truncate authorized_keys
      command: truncate -s 0 /home/vagrant/.ssh/authorized_keys

    - name: Add public key to authorized_keys
      lineinfile:
        path: /home/vagrant/.ssh/authorized_keys
        line: "{{ lookup('file', '/home/vagrant/admin_ssh.pub') }}"
        create: yes
    
    - name: Delete admin_ssh.pub
      file:
        path: /home/vagrant/admin_ssh.pub
        state: absent

    - name: Enable UFW (Uncomplicated Firewall)
      ufw:
        state: enabled

    - name: Configure firewall
      ufw:
        logging: on

    - name: Allow incoming traffic betwen port 3306 and hosts db, ca, log
      ufw:
        rule: allow
        proto: tcp
        port: "443"
        src: '{{ item }}'
      loop:
        - 192.168.56.12
        - 192.168.56.13 
        - 192.168.56.15

    - name: Allow incoming traffic to port 22 from web
      ufw:
        rule: limit
        proto: tcp
        port: ssh
        src: 192.168.56.11

    - name: Drop all other incoming traffic
      ufw:
        rule: deny
        direction: in

    - name: Drop all other outgoing traffic
      ufw:
        rule: deny
        direction: out

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted