# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

version: "1"

global:
  scheduler: crond

default:
  repository-file: /run/secrets/db_bak_repository
  password-file: /run/secrets/db_bak_password
  cacert: /run/secrets/ca_root_cert
  initialize: true

  backup:
    verbose: true
    source: /resticprofile
    schedule: "*:00,15,30,45"
    schedule-permission: user
