services:
  server:
    build:
      context: server
    restart: unless-stopped
    hostname: ca
    secrets:
      - ca-root-cert
      - ca-root-key
      - ca-cert
      - ca-key
    volumes:
      - ca-data:/app/data
      - ./secrets/admin.imovies.ch.crt:/app/data/clients/admin/310629842216214876788742898011996388621811897248_cert.crt:ro
    environment:
      - TZ=Etc/UTC
      - BAK_HOST=bak.imovies.ch:443
      - LOG_HOST=log.imovies.ch:514
    ports:
      - "${CA_PORT}:8000"
    user: 10001:10001
  scheduled-backup:
    image: creativeprojects/resticprofile:latest
    restart: unless-stopped
    hostname: ca
    secrets:
      - ca-root-cert
      - ca-bak-repository
      - ca-bak-password
    volumes:
      - ./scheduled-backup/profiles.yaml:/etc/resticprofile/profiles.yaml:ro
      - ca-data:/resticprofile/ca-data
    environment:
      - TZ=Etc/UTC
    entrypoint: /bin/sh
    command: ['-c', 'resticprofile schedule --all && crond -f']
    user: 0:0  # 'resticprofile schedule' requires root
volumes:
  ca-data:
secrets:
  ca-root-cert:
    file: secrets/root.imovies.ch.crt
  ca-root-key:
    file: secrets/root.imovies.ch.key
  ca-cert:
    file: secrets/ca.imovies.ch.crt
  ca-key:
    file: secrets/ca.imovies.ch.key
  ca-bak-repository:
    file: secrets/bak_repository.txt
  ca-bak-password:
    file: secrets/bak_password.txt
