services:
  server:
    build:
      context: server
    restart: unless-stopped
    hostname: ca
    secrets:
      - ca_root_cert
      - ca_root_key
      - ca_cert
      - ca_key
    volumes:
      - ca_data:/app/data
      - ./secrets/admin.imovies.ch.crt:/app/data/clients/admin/15654392993111371456575333615027215480854870364_cert.crt:ro
    environment:
      - TZ=Etc/UTC
      - BAK_HOST=bak.imovies.ch:443
      - LOG_HOST=log.imovies.ch:514
    ports:
      - "${CA_PORT}:8000"
    user: 10001:10001
  scheduled-backup:
    image: creativeprojects/resticprofile:latest
    restart: unless-stopped
    hostname: ca
    secrets:
      - ca_root_cert
      - ca_bak_repository
      - ca_bak_password
    volumes:
      - ./scheduled-backup/profiles.yaml:/etc/resticprofile/profiles.yaml:ro
      - ca_data:/resticprofile/ca_data
    environment:
      - TZ=Etc/UTC
    entrypoint: /bin/sh
    command: ['-c', 'resticprofile schedule --all && crond -f']
    user: 0:0  # 'resticprofile schedule' requires root
volumes:
  ca_data:
secrets:
  ca_root_cert:
    file: secrets/root.imovies.ch.crt
  ca_root_key:
    file: secrets/root.imovies.ch.key
  ca_cert:
    file: secrets/ca.imovies.ch.crt
  ca_key:
    file: secrets/ca.imovies.ch.key
  ca_bak_repository:
    file: secrets/bak_repository.txt
  ca_bak_password:
    file: secrets/bak_password.txt
