services:
  server:
    build:
      context: server
    volumes:
      - ./certs:/app/certs
      - ca-data:/app/data
      - ./certs/admin.imovies.ch.pem:/app/data/clients/admin/14785487178505059841_cert.pem
    ports:
      - "${CA_PORT}:8000"
volumes:
  ca-data:
