services:
  db:
    image: mysql:latest
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./imovies_users.dump:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=imovies
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
volumes:
  db-data:
secrets:
  db-password:
    file: db_password.txt
