services:
  server:
    image: mysql:latest
    restart: unless-stopped
    hostname: db
    secrets:
      - ca_root_cert
      - db_cert
      - db_key
      - db_root_password
      - db_password
    volumes:
      - ./server/imovies_users.dump:/docker-entrypoint-initdb.d/init.sql:ro
      - ./server/update.sql:/docker-entrypoint-initdb.d/update.sql:ro
      - db_data:/var/lib/mysql
      - db_logs:/var/lib/mysql-files
    environment:
      - TZ=Etc/UTC
      - MYSQL_DATABASE=imovies
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_USER=web
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    command:
      - --default-authentication-plugin=caching_sha2_password
      - --ssl-ca=/run/secrets/ca_root_cert
      - --ssl-cert=/run/secrets/db_cert
      - --ssl-key=/run/secrets/db_key
      - --require-secure-transport=ON
      - --log_error=/var/lib/mysql-files/error.log
      - --general-log=1
      - --general-log_file=/var/lib/mysql-files/general.log
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password="$$(cat /run/secrets/db_root_password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    user: 999:999
  scheduled-backup:
    image: creativeprojects/resticprofile:latest
    restart: unless-stopped
    hostname: db
    secrets:
      - ca_root_cert
      - db_bak_repository
      - db_bak_password
    volumes:
      - ./scheduled-backup/profiles.yaml:/etc/resticprofile/profiles.yaml:ro
      - db_data:/resticprofile/db_data
    environment:
      - TZ=Etc/UTC
    entrypoint: /bin/sh
    command: ['-c', 'resticprofile schedule --all && crond -f']
    user: 0:0  # Requires root to run 'resticprofile schedule'
  logger:
    platform: linux/amd64
    build:
      context: logger
    restart: unless-stopped
    hostname: db
    secrets:
      - ca_root_cert
    volumes:
      - ./logger/rsyslog.conf:/etc/rsyslog.conf:ro
      - db_logs:/var/log/mysql
    environment:
      - TZ=Etc/UTC
      - CONTAINER_SILENT=on
    user: 0:0  # Requires root to read db_logs
secrets:
  ca_root_cert:
    file: secrets/root.imovies.ch.crt
  db_cert:
    file: secrets/db.imovies.ch.crt
  db_key:
    file: secrets/db.imovies.ch.key
  db_root_password:
    file: secrets/db_root_password.txt
  db_password:
    file: secrets/db_password.txt
  db_bak_repository:
    file: secrets/bak_repository.txt
  db_bak_password:
    file: secrets/bak_password.txt
volumes:
  db_data:
  db_logs:
