services:
  db:
    image: mysql:latest
    restart: always
    secrets:
      - db-password
    volumes:
      - ./imovies_users.dump:/docker-entrypoint-initdb.d/init.sql:ro
      - ./certs:/etc/certs:ro
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=imovies
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
  scheduled-backup:
    image: creativeprojects/resticprofile:latest
    entrypoint: '/bin/sh'
    command:
      - '-c'
      - 'resticprofile schedule --all && crond -f'
    volumes:
      - ./profiles.yaml:/etc/resticprofile/profiles.yaml:ro
      - ./bak_repository.txt:/etc/resticprofile/bak_repository.txt:ro
      - ./bak_password.txt:/etc/resticprofile/bak_password.txt:ro
      - ./certs:/etc/certs:ro
      - db-data:/resticprofile/db-data
    environment:
      - TZ=Etc/UTC
secrets:
  db-password:
    file: db_password.txt
volumes:
  db-data:
