services:
  server:
    image: mysql:latest
    restart: unless-stopped
    hostname: db
    secrets:
      - db-root-password
      - db-password
    volumes:
      - ./imovies_users.dump:/docker-entrypoint-initdb.d/init.sql:ro
      - ./update.sql:/docker-entrypoint-initdb.d/update.sql:ro
      - ./certs:/etc/ssl/certs:ro
      - db-data:/var/lib/mysql
      - db-logs:/var/lib/mysql-files
    environment:
      - TZ=Etc/UTC
      - MYSQL_DATABASE=imovies
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-root-password
      - MYSQL_USER=web
      - MYSQL_PASSWORD_FILE=/run/secrets/db-password
    command:
      - --default-authentication-plugin=caching_sha2_password
      - --ssl-ca=/etc/ssl/certs/root.imovies.ch.crt
      - --ssl-cert=/etc/ssl/certs/db.imovies.ch.crt
      - --ssl-key=/etc/ssl/certs/db.imovies.ch.key
      - --require-secure-transport=ON
      - --log-error=/var/lib/mysql-files/error.log
      - --general-log=1
      - --general-log-file=/var/lib/mysql-files/general.log
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password="$$(cat /run/secrets/db-root-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    user: 999:999
  scheduled-backup:
    image: creativeprojects/resticprofile:latest
    restart: unless-stopped
    hostname: db
    volumes:
      - ./profiles.yaml:/etc/resticprofile/profiles.yaml:ro
      - ./bak_repository.txt:/etc/resticprofile/bak_repository.txt:ro
      - ./bak_password.txt:/etc/resticprofile/bak_password.txt:ro
      - ./certs:/etc/ssl/certs:ro
      - db-data:/resticprofile/db-data
    environment:
      - TZ=Etc/UTC
    entrypoint: /bin/sh
    command: ['-c', 'resticprofile schedule --all && crond -f']
    user: 0:0  # Requires root to run 'resticprofile schedule'
  logger:
    build:
      context: logger
    restart: unless-stopped
    hostname: db
    volumes:
      - ./logger/rsyslog.conf:/etc/rsyslog.conf:ro
      - ./certs:/etc/ssl/certs:ro
      - db-logs:/var/log/mysql
    environment:
      - TZ=Etc/UTC
      - CONTAINER_SILENT=on
    user: 0:0  # Requires root to read db-logs
secrets:
  db-root-password:
    file: db_root_password.txt
  db-password:
    file: db_password.txt
volumes:
  db-data:
  db-logs:
