services:
  server:
    image: mysql:latest
    restart: unless-stopped
    command: ['--ssl-ca=/etc/ssl/certs/root.imovies.ch.crt', '--ssl-cert=/etc/ssl/certs/db.imovies.ch.crt', '--ssl-key=/etc/ssl/certs/db.imovies.ch.key', '--require-secure-transport=ON']
    secrets:
      - db-root-password
      - db-password
    volumes:
      - ./imovies_users.dump:/docker-entrypoint-initdb.d/init.sql:ro
      - ./insert_admin.sql:/docker-entrypoint-initdb.d/insert_admin.sql:ro
      - ./certs:/etc/ssl/certs:ro
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=imovies
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-root-password
      - MYSQL_USER=web
      - MYSQL_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-root-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    user: 999:999
  scheduled-backup:
    image: creativeprojects/resticprofile:latest
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
    entrypoint: /bin/sh
    command: ['-c', 'resticprofile schedule --all && crond -f']
    volumes:
      - ./profiles.yaml:/etc/resticprofile/profiles.yaml:ro
      - ./bak_repository.txt:/etc/resticprofile/bak_repository.txt:ro
      - ./bak_password.txt:/etc/resticprofile/bak_password.txt:ro
      - ./certs:/etc/ssl/certs:ro
      - db-data:/resticprofile/db-data
    user: 0:0  # 'resticprofile schedule' requires root
secrets:
  db-root-password:
    file: db_root_password.txt
  db-password:
    file: db_password.txt
volumes:
  db-data:
