---
- name: Provision VirtualBox Ubuntu machine and set up WireGuard container
  hosts: wireguard
  become: yes

  tasks:
    - name: Update apt repositories
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Copy the docker-compose.yml file to the remote host
      copy:
        src: /home/rembrandt/Documents/Projektid/GitProjects/ethz-applied-security-laboratory-2023/vagrant/docker-compose.yml
        dest: /home/vagrant/docker-compose.yml
        owner: vagrant
        group: docker
        mode: "0644"

    - name: Start the container using Docker Compose
      command: "docker-compose up -d"
    
    - name: Copy peer configuration file from WireGuard VM
      fetch:
        src: /home/vagrant/config/peer1/peer1.conf
        dest: ./
        flat: true
    - name: Copy peer configuration file from WireGuard VM
      fetch:
        src: /home/vagrant/config/peer2/peer2.conf
        dest: ./
        flat: true