services:
  server:
    build:
      context: .
    secrets:
      - db-password
      - web-secret-key
    environment:
      - DATABASE_DB=imovies
      - DATABASE_USER=root
      - DATABASE_PASSWORD_FILE=/run/secrets/db-password
      - DATABASE_HOST=127.0.0.1
      - CA_HOST=127.0.0.1
      - WEB_SECRET_KEY_FILE=/run/secrets/web-secret-key
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "${WEB_PORT}:443"
    volumes:
      - ./nginx:/etc/nginx
    # depends_on:
    #   server:
    #     condition: service_started
secrets:
  db-password:
    file: db_password.txt
  web-secret-key:
    file: web_secret_key.txt
