services:
  server:
    build:
      context: server
    secrets:
      - db-password
      - web-secret-key
      - web-csrf-secret-key
    environment:
      - DATABASE_DB=imovies
      - DATABASE_USER=web
      - DATABASE_PASSWORD_FILE=/run/secrets/db-password
      - DATABASE_HOST=db.imovies.ch
      - CA_HOST=ca.imovies.ch
      - WEB_SECRET_KEY_FILE=/run/secrets/web-secret-key
      - WEB_CSRF_SECRET_KEY_FILE=/run/secrets/web-csrf-secret-key
    volumes:
      - ./certs:/etc/ssl/certs:ro
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - "${WEB_PORT}:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs:ro
secrets:
  db-password:
    file: db_password.txt
  web-secret-key:
    file: web_secret_key.txt
  web-csrf-secret-key:
    file: web_csrf_secret_key.txt
