services:
  server:
    build:
      context: server
    restart: unless-stopped
    hostname: web
    secrets:
      - ca-root-cert
      - db-password
      - web-secret-key
      - web-csrf-secret-key
    environment:
      - TZ=Etc/UTC
      - DATABASE_DB=imovies
      - DATABASE_USER=web
      - DATABASE_PASSWORD_FILE=/run/secrets/db-password
      - DATABASE_HOST=db.imovies.ch:3306
      - CA_HOST=ca.imovies.ch:443
      - LOG_HOST=log.imovies.ch:514
      - WEB_SECRET_KEY_FILE=/run/secrets/web-secret-key
      - WEB_CSRF_SECRET_KEY_FILE=/run/secrets/web-csrf-secret-key
    user: 10001:10001
  proxy:
    image: nginxinc/nginx-unprivileged:latest
    restart: unless-stopped
    hostname: web
    secrets:
      - ca-root-cert
      - web-cert
      - web-key
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - TZ=Etc/UTC
      - WEB_SERVER_NAME=imovies.ch
      - WEB_SERVER_HOST=server:8000
    ports:
      - "${WEB_PORT}:8000"
    user: 101:101
secrets:
  ca-root-cert:
    file: secrets/root.imovies.ch.crt
  db-password:
    file: secrets/db_password.txt
  web-secret-key:
    file: secrets/web_secret_key.txt
  web-csrf-secret-key:
    file: secrets/web_csrf_secret_key.txt
  web-cert:
    file: secrets/web.imovies.ch.crt
  web-key:
    file: secrets/web.imovies.ch.key
